version: "3.7"
services:
  app:
    container_name: nestjs-boilerplate-app
    build:
      context: ./
      dockerfile: ./docker-files/DockerFile
    command: ['npm', 'run', 'start:dev']
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: 'local'
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    command: --quiet
